name: Dusk tests

on:
  pull_request:
    branches:
      - main

jobs:
  dusk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Copy .env file
        run: cp .env.dusk.testing .env

      - name: Configure Composer cache
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-suggest --no-progress --prefer-dist --optimize-autoloader

      - name: Configure NPM cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 12.x

      - name: Install NPM dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Compile NPM dependencies
        run: npm run build

      - name: Configure Laravel environment
        run: |
          php artisan key:generate
          touch database/database.sqlite

      - name: Upgrade Chrome driver
        run: php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`

      - name: Start Chrome driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel server
        run: php artisan serve &

      - name: Run Dusk tests
        run: php artisan dusk --stop-on-failure

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Logs
          path: ./storage/logs

      - name: Upload failure screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Screenshots
          path: ./tests/Browser/screenshots
